export * from "./controllers/adminLogout"
export * from "./controllers/salonLists"
export * from "./controllers/salonDetails"
export * from "./controllers/acceptSalon"
export * from "./controllers/deleteSalon"